export const CATEGORIAS_OPENTDB = [
    { id: "", nome: "Qualquer Tema (Aleatório)" },
    { id: 9, nome: "Conhecimentos Gerais" },
    { id: 10, nome: "Entretenimento: Livros" },
    { id: 11, nome: "Entretenimento: Filmes" },
    { id: 12, nome: "Entretenimento: Música" },
    { id: 13, nome: "Entretenimento: Musicais e Teatros" },
    { id: 14, nome: "Entretenimento: Televisão" },
    { id: 15, nome: "Entretenimento: Video Games" },
    { id: 16, nome: "Entretenimento: Jogos de Tabuleiro" },
    { id: 17, nome: "Ciência e Natureza" },
    { id: 18, nome: "Ciência: Computadores" },
    { id: 19, nome: "Ciência: Matemática" },
    { id: 20, nome: "Mitologia" },
    { id: 21, nome: "Esportes" },
    { id: 22, nome: "Geografia" },
    { id: 23, nome: "História" },
    { id: 24, nome: "Política" },
    { id: 25, nome: "Arte" },
    { id: 26, nome: "Celebridades" },
    { id: 27, nome: "Animais" },
    { id: 28, nome: "Veículos" },
    { id: 29, nome: "Entretenimento: Quadrinhos" },
    { id: 30, nome: "Ciência: Gadgets" },
    { id: 31, nome: "Entretenimento: Anime e Mangá Japonês" },
    { id: 32, nome: "Entretenimento: Desenhos Animados" }
];